version: 2

models:
  - name: mart_tickets_enriched
    columns:
      - name: ticket_id
        tests:
          - unique
          - not_null
      - name: sentiment_score
        tests:
          - not_null
      - name: sentiment_bucket
        tests:
          - not_null
          - accepted_values:
              values: ['positive', 'negative', 'neutral']

  - name: mart_tickets_classified
    columns:
      - name: ticket_id
        tests:
          - unique
          - not_null
      - name: ticket_category
        tests:
          - not_null
          - accepted_values:
              values: ['Billing Issue', 'Technical Support', 'Feature Request', 'Account Access', 'General Inquiry']

  - name: mart_call_notes_extracted
    columns:
      - name: note_id
        tests:
          - unique
          - not_null
      - name: customer_name
        tests:
          - not_null

  - name: mart_reviews_analyzed
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: urgency
        tests:
          - accepted_values:
              values: ['high', 'medium', 'low']

  - name: mart_weekly_ticket_themes
    columns:
      - name: week
        tests:
          - not_null
      - name: ticket_category
        tests:
          - not_null
      - name: weekly_themes
        tests:
          - not_null
